trigger:
  branches:
    include:
      - main

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'windows-latest'

steps:

- task: Checkout@1

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# 🔧 Restore project
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# 🔨 Build project
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# 🧪 Run tests with code coverage
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --collect:"Code Coverage"'

# 📦 Publish build output
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

# 🚚 Upload artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# 🧪 Deploy to mocked environments
- script: echo "✅ Deploying to Dev Environment on port 5000"
  displayName: 'Deploy to Dev Environment'

- script: echo "✅ Deploying to QAT Environment"
  displayName: 'Deploy to QAT Environment'

- script: echo "✅ Deploying to Staging Environment"
  displayName: 'Deploy to Staging Environment'

- script: echo "✅ Deploying to Production Environment"
  displayName: 'Deploy to Production Environment'
